version: "3.8"

services:
  php:
    build: ./docker
    container_name: pdf-generator-php
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: pdf-generator-nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    restart: unless-stopped